import { LoanState, ProposalType } from "./types";

export const proposal: ProposalType = {
    borrower: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
    token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
    principal: 50,
    interest: 1.5,
    lengthDays: 365,
    lender: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
    fundDay: 0,
    repayDay: 10,
    state: LoanState.UNFUNDED,
    id: "3",
    title: "title of loan",
    description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
};

export const fundedProposals: ProposalType[] = [
    {
        borrower: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 1000,
        interest: 1,
        lengthDays: 180,
        lender: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "1",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        borrower: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 50,
        interest: 1.5,
        lengthDays: 365,
        lender: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "2",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        borrower: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 50,
        interest: 1.5,
        lengthDays: 365,
        lender: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "3",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
];

export const createdProposals: ProposalType[] = [
    {
        borrower: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 1000,
        interest: 1,
        lengthDays: 180,
        lender: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "3",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        borrower: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 50,
        interest: 1.5,
        lengthDays: 365,
        lender: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "3",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
];

export const exploreProposals: ProposalType[] = [
    {
        borrower: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 1000,
        interest: 1,
        lengthDays: 180,
        lender: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "3",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        borrower: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 50,
        interest: 1.5,
        lengthDays: 365,
        lender: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "3",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        borrower: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 50,
        interest: 1.5,
        lengthDays: 365,
        lender: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "3",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        borrower: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 1000,
        interest: 1,
        lengthDays: 180,
        lender: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "3",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        borrower: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 50,
        interest: 1.5,
        lengthDays: 365,
        lender: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "3",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    {
        borrower: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
        token: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
        principal: 50,
        interest: 1.5,
        lengthDays: 365,
        lender: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
        fundDay: 0,
        repayDay: 10,
        state: LoanState.UNFUNDED,
        id: "3",
        title: "title of loan",
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
];
